/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import java.awt.Toolkit;
import java.awt.Image;

/**
 *
 * @author alber
 */
public class vistaSeleccionados extends javax.swing.JFrame {

    vistaEscogerProblema viewEscogerProblema = new vistaEscogerProblema();

    /**
     * Creates new form vistaSeleccionados
     */
    public vistaSeleccionados() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Icono y titulo del frame
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/logoCAMS.png"));
        this.setIconImage(icono);
        this.setTitle("Concurso Anual de Matemáticas del Sureste");
        setExtendedState(MAXIMIZED_BOTH);
        jTableSeleccionados.getTableHeader().setPreferredSize(new Dimension(10, 40));
        jTableSeleccionados.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 25));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombres = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSeleccionados = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNombres.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelNombres.setText("Seleccionar 2 participantes");

        jTableSeleccionados.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jTableSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSeleccionados.setRowHeight(45);
        jScrollPane1.setViewportView(jTableSeleccionados);

        btnAceptar.setBackground(new java.awt.Color(51, 204, 255));
        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jLabelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabelNombres)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int cantidad = numRegistrosSeleccionados();
        if (cantidad == 2) {
            this.setVisible(false);
            // le pasamos los nombres de los 2 alumnos seleccionados
            viewEscogerProblema.setArraySeleccionados(getParejaSeleccionados());
            viewEscogerProblema.generarMatrizNumProblemasExtras();
            viewEscogerProblema.mostrarTabla();
            viewEscogerProblema.setVisible(true);
        } else {
            if (cantidad < 2) {
                int resta = 2 - cantidad;
                if (resta != 1) {
                    JOptionPane.showMessageDialog(null, "Debe de seleccionar " + resta + " alumnos más");
                } else {
                    JOptionPane.showMessageDialog(null, "Debe de seleccionar " + resta + " alumno más");
                }
            } else {
                int resta = cantidad - 2;
                if (resta != 1) {
                    JOptionPane.showMessageDialog(null, "Debe de seleccionar " + resta + " alumnos menos");
                } else {
                    JOptionPane.showMessageDialog(null, "Debe de seleccionar " + resta + " alumno menos");
                }
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    // método que devuelve el número de alumnos seleccionados
    public int numRegistrosSeleccionados() {
        int numRegistros = 0;
        for (int i = 0; i < jTableSeleccionados.getRowCount(); i++) {
            String seleccion = String.valueOf(jTableSeleccionados.getValueAt(i, 3));
            if (seleccion.equals("true")) {
                numRegistros++;
            }
        }
        return numRegistros;
    }

    // función que devuelve el nombre de los 2 estudiantes seleccionados
    public String[] getParejaSeleccionados() {
        String infoAlumnos[] = new String[2];
        int k = 0;
        for (int i = 0; i < jTableSeleccionados.getRowCount(); i++) {
            String seleccion = String.valueOf(jTableSeleccionados.getValueAt(i, 3));
            if (seleccion.equals("true")) {
                infoAlumnos[k] = String.valueOf(jTableSeleccionados.getValueAt(i, 0)); //nombre                
                k++;
            }
            if (k == 2) {
                break;
            }
        }
        return infoAlumnos;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaSeleccionados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaSeleccionados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaSeleccionados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaSeleccionados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaSeleccionados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabelNombres;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableSeleccionados;
    // End of variables declaration//GEN-END:variables

    public void agregarCheckBox(int columna, JTable tabla) {
        TableColumn tc = tabla.getColumnModel().getColumn(columna);
        tc.setCellEditor(tabla.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(tabla.getDefaultRenderer(Boolean.class));
    }

    public boolean isSelected(int row, int column, JTable tabla) {
        return tabla.getValueAt(row, column) != null;
    }
}
