/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.manipularCSV;
import java.awt.Dimension;
import java.awt.Font;

/**
 *
 * @author alber
 */
public class vistaParejas extends javax.swing.JFrame {

    String[][] matrizParejas = new String[5][8];
    vistaProblemas viewProblemas = new vistaProblemas();
    manipularCSV modelo = new manipularCSV();

    /**
     * Creates new form vistaParejas
     */
    public vistaParejas() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        jTableParejas.getTableHeader().setPreferredSize(new Dimension(10, 40));
        jTableParejas.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 30));
    }

    public void setMatrizParejas(String[][] matrizParejas) {
        this.matrizParejas = matrizParejas;
    }

    //devuelve la matriz de parejas únicamente con el nombre de los participantes 
    public String[][] getMatrizParejas() {
        String[][] matrizNombreParejas = new String[5][2];
        System.out.println("");
        System.out.println("Matriz Vista Parejas:");
        for (int i = 0; i < matrizNombreParejas.length; i++) {
            int k = 0;
            for (int j = 0; j < matrizNombreParejas[i].length; j++) {
                matrizNombreParejas[i][j] = matrizParejas[i][k];
                k = k + 4;
                System.out.print(matrizNombreParejas[i][j] + ",");
            }
            System.out.println("");
        }
        // le pasamos a la clase vistaProblemas la matriz de parejas 
        //viewProblemas.setMatrizNombreParejas(matrizNombreParejas);                
        return matrizNombreParejas;
    }

    public void mostrarMatriz() {
        jTableParejas.setModel(new javax.swing.table.DefaultTableModel(
                getMatrizParejas(),
                new String[]{
                    "Participantes A", "Participantes B"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelParejas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableParejas = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabelParejas.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabelParejas.setText("Parejas");

        jTableParejas.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jTableParejas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Participantes A", "Participantes B"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableParejas.setMaximumSize(new java.awt.Dimension(500, 500));
        jTableParejas.setMinimumSize(new java.awt.Dimension(500, 380));
        jTableParejas.setPreferredSize(new java.awt.Dimension(500, 400));
        jTableParejas.setRowHeight(80);
        jScrollPane1.setViewportView(jTableParejas);

        btnAceptar.setBackground(new java.awt.Color(102, 255, 255));
        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabelParejas)
                .addGap(0, 96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelParejas)
                .addGap(200, 200, 200)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaParejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaParejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaParejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaParejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaParejas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabelParejas;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableParejas;
    // End of variables declaration//GEN-END:variables
}
