/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.manipularCSV;

/**
 *
 * @author alber
 */
public class vistaConfirmacionParticipantes extends javax.swing.JFrame {    
    manipularCSV modelo = new manipularCSV();
    vistaParejas viewParejas = new vistaParejas();
    String [][] matrizSeleccionados = new String[10][4];
    String [][] matrizParejas = new String[5][8];
    String [][] matrizImpresionParejas = new String[15][3];
    /**
     * Creates new form vistaonfirmacionParticipantes
     */
    public vistaConfirmacionParticipantes() {
        initComponents();
        this.setLocationRelativeTo(null);        
    }

    public String[][] getMatrizParticipantes() {
        return matrizSeleccionados;
    }    
    
    public void setMatrizParticipantes(String[][] matrizParticipantes) {
        this.matrizSeleccionados = matrizParticipantes;
    }
    
    public String[][] getMatrizParejas(){
        return matrizParejas;
    }
    
    public void setMatrizParejas(String[][] matrizParejas) {
        this.matrizParejas = matrizParejas;
    }

    public String[][] getMatrizImpresionParejas() {
        return matrizImpresionParejas;
    }

    public void setMatrizImpresionParejas(String[][] matrizImpresionParejas) {
        this.matrizImpresionParejas = matrizImpresionParejas;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("A continuación se generará la lista de parejas con los");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("¿Desea continuar?");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("participantes seleccionados");

        btnAceptar.setBackground(new java.awt.Color(102, 255, 102));
        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 0, 51));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        crearMatrizParejas();  
        crearMatrizImpresionParejas();
        // creamos el archivo PAREJAS.csv
        modelo.escribirEnFichero(getMatrizParejas(), modelo.obtenerRutaGuardadoArchivos(), "PAREJAS", "csv");   
        // creamos el archivo IMPRESION_PAREJAS.csv
        modelo.escribirEnFichero(getMatrizImpresionParejas(), modelo.obtenerRutaGuardadoArchivos(), "IMPRESION_PAREJAS", "csv");   
        this.dispose();     
        viewParejas.setMatrizParejas(getMatrizParejas());  
        viewParejas.mostrarMatriz();
        viewParejas.setVisible(true);        
    }//GEN-LAST:event_btnAceptarActionPerformed

    // función que crea la matriz del archivo PAREJAS.csv
    public void crearMatrizParejas(){    
        System.out.println("Matriz informacion de PAREJAS.csv: ");
        int k = 5;        
        for (int i=0;i<matrizParejas.length;i++){
            int m = 0;
            for(int j=0;j<matrizParejas[i].length;j++){
                if (j<4){
                    matrizParejas[i][j] = matrizSeleccionados[i][j]; 
                }else{
                    matrizParejas[i][j] = matrizSeleccionados[k][m];
                    m++;
                }  
                System.out.print(matrizParejas[i][j]+",");              
            }   
            k++;
            System.out.println("");
        }             
    }
    
    // función que crea la matriz del archivo IMPRESION_PAREJAS.csv
    public void crearMatrizImpresionParejas(){        
        matrizImpresionParejas[0][0] = "Participantes A";
        matrizImpresionParejas[9][0] = "Participantes B";
        matrizImpresionParejas[0][1] = "";
        matrizImpresionParejas[0][2] = "";
        
        matrizImpresionParejas[6][0] = "";
        matrizImpresionParejas[7][0] = "";
        matrizImpresionParejas[8][0] = "";
        
        // llenamos los contadores de la columna A
        int fila = 1;
        for (int i=0;i<2;i++){
            int num = 1;
            for (int j=0;j<5;j++){
                matrizImpresionParejas[fila][0] = ""+num;
                num++;
                fila++;
            }
            fila = 10;
        }
        
        // llenamos nombre de estudiante y escuela
        int k = 0; 
        
        for (int i=1;i<15;i++){
            int m = 0;
            for (int j=1;j<3;j++){
                if (i>5 && i<10){
                    matrizImpresionParejas[i][j] = "";
                }else{
                    matrizImpresionParejas[i][j] = matrizSeleccionados[k][m];
                    m++;
                }                           
            }
            if (i<6 || i>9){
                k++;
            }            
        }           
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaConfirmacionParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaConfirmacionParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaConfirmacionParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaConfirmacionParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaConfirmacionParticipantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
